version: '3'
services:


    mysql:
        image: mysql:5.7
        environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=root


    mserver:
        ports:
            - "7777:7777"
        build:
            context: .
            dockerfile: dockerfile_server_dev
