version: '3'
services:
    redis:
      image: "redis:alpine"
      
    mserver:
        build:
            context: .
            dockerfile: dockerfile_server_dev
        ports:
            - "7777:7777"