version: '3'
services:
    mserver_server:
        container_name: mserver_server
        ports:
            - "7777:7777"
        build:
            context: .
            dockerfile: dockerfile_server
    # vault1: